import 'package:get/get_navigation/src/root/internacionalization.dart';

class AppString extends Translations {
  //translator instance;

  /// labels
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'appName': 'Community',
          'slogan': 'Connecting Communities, Empowering Lives',
          'startYourJourney': 'Start your journey with us.',
          'itBringsTogether':
              'It brings together your tasks, projects, timelines, files and more',
          'welcome': 'Welcome to RSM',
          'createdBy': '© 2025 rsm. Crafted with  by RSM',
          'welcomeBack': 'Welcome Back',
          'signInPrompt': 'Sign in to continue to RSM.',
          'username': 'Username',
          'password': 'Password',
          'email': 'Email',
          'forgotPassword': 'Forgot Password?',
          'signIn': 'Sign In',
          'signUp': 'Sign Up',
          'rememberMe': 'Remember me',
          'signInWith': 'Sign In with',
          'dontHaveAccount': 'Don\'t have an account?',
          'createAccount': 'Create your free account',
          'getFreeAccount': 'Get your free RSM account now',
          'termsAndConditions': 'By registering you agree to the RSM',
          'termsOfUse': 'Terms of Use',
          'createAccountWith': 'Create account with',
          'alreadyHaveAccount': 'Already have an account?',
          'buildingAndSocieties': 'Building & Societies',
          'recentlyAddedProperty': 'Recently Added Property',
          'sortBy': 'Sort By',
          'customerFeedback': 'Customer Feedback',
          'viewAll': 'View All',
          'facilities': 'Facilities',
          'viewProfile': 'View Profile',
          'totalUnpaidInvoices': 'Total unpaid invoices',
          'totalReceivable': 'Total Receivable',
          'recentActivity': 'Recent Activity',
          'vendorList': 'Vendor List',
          'propertyManagement': 'Property Management',
          'property': 'Property',
          'readMore': 'Read More',
          'addProperty': 'Add Property',
          'propertyImages': 'Property Images',
          'propertyTitle': 'Property Title',
          'shortName': 'Short Name',
          'propertyType': 'Property Type',
          'block': 'Block',
          'unit': 'Unit',
          'location': 'Location',
          'area': 'Area',
          'city': 'City',
          'remarks': 'Remarks',
          'filter': 'Filter',
          'apply': 'Apply',
          'close': 'Close',
          'bedroom': 'Bedroom',
          'features': 'Features',
          'bathroom': 'Bathroom',
          'propertyOverview': 'Property Overview',
          'propertyFeatures': 'Property Features',
          'propertyLocation': 'Property Location',
          'getInTouch': 'Get in Touch',
          'agentDetails': 'Agent Details',
          'ownerHistory': 'Owner History',
          'vendors': 'Vendors',
          'status': 'Status',
          'addAgent': 'Add Agent',
          'message': 'Message',
          'phone': 'Phone',
          'agentImages': 'Agent Images',
          'agentName': 'Agent Name',
          'sontactNumber': 'Contact Number',
          'address': 'Address',
          'vendorDetail': 'Vendor Detail',
          'activeListing': 'Active Listing',
          'tenantSetup': 'Tenant Setup',
          'residentManagement': 'Resident Management',
          'addCommunities': 'Add Communities',
          'staff': 'Staff',
          'user': 'User',
          'resident': 'Resident',
          'addHr': 'Add HR',
          'visitorManagement': 'Visitor Management',
          'parkingManagement': 'Parking Management',
          'ticketsList': 'Tickets List',
          'listView': 'List View',
          'accounting': 'Accounting',
          'addProduct': 'Add Product',
          'productsGrid': 'Products Grid',
          'inventoryOverview': 'Inventory Overview',
          "description": 'Description:',
          'productDetails': 'Product Details:',
          'addReview': 'Add Review',
          'ratingsReviews': 'Ratings & Reviews',
          'invoiceList': 'Invoice List',
          'generateInvoice': 'Generate Invoice',
          'invoiceReceiving': 'Invoice Receiving',
          'postInvoice': 'Post Invoice',
          'getList': 'Get List',
          'earning': 'Earning',
          'print': 'Print',
          'download': 'Download',
          'invoice': 'Invoice',
          'totalOrderAmount': 'Total order amount',
          'orderStatus': 'Order Status',
          'firstName': 'First Name',
          'middleName': 'Middle Name',
          'lastName': 'Last Name',
          'loginId': 'Login ID',
          'contactNumber': 'Contact Number',
          'dateOfBirth': 'Date of Birth',
          'addressLine1': 'Address Line 1',
          'addressLine2': 'Address Line 2',
          'addressLine3': 'Address Line 3',
          'country': 'Country',
          'confirmEmailAddress': 'Confirm Email Address',
          'forgetPasswordLabel':
              'Enter your official email or login ID to receive a One-Time Password.',
          'enterOneTimePassword': 'Enter One-Time Password',
          'enterOTPLabel': 'Enter the OTP sent to your email: ',
          'didntReciveCode': 'Did not receive the code? ',
          'resendCode': 'Resend Code',
          'expiresIn': 'Expires in ',
          'createPassword': 'Create New Password',
          'createPasswordLabel':
              'Create a new password as per the security requirements.',
          'reEnterPassword': 'Re-enter Password',
          'createStrongPassword': 'Create strong password using:',
          'backToSignIn': 'Back to Sign in',
          'emailAddress': 'Email Address',
          'next': 'Next',
          'editProfile': 'Edit Profile',
          'save': 'Save',
          'saveChanges': 'Save Changes',
          'submit': 'Submit',
          'cancel': 'Cancel',
          'add': 'Add',
          'addRealEstate': 'Add Real Estate',
          'realEstateName': 'Real Estate Name',
          'realEstateCategory': 'Real Estate Category',
          'realEstateType': 'Real Estate Type',
          'realEstate': 'Real Estate',
          'selectRealEstateName': 'Select Real Estate Name',
          'selectLocation': 'Select Location',
          'select': 'Select',
          'blockName': 'Block Name',
          'addNewBlock': 'Add New Block',
          'unitName': 'Unit Name',
          'addNewUnit': 'Add New Unit',
          'facility': 'Facility',
          'addNewFacility': 'Add New Facility',
          'facilityName': 'Facility Name',
          'street': 'Street',
          'plotNo': 'Plot No',
          'unitNo': 'Unit No',
          'floorNo': 'Floor No',
          'bedrooms': 'Bedrooms',
          'bathrooms': 'Bathrooms',
          'carParks': 'Car Parks',
          'addVendor': 'Add Vendor',
          'vendorName': 'Vendor Name',
          'category': 'Category',
          'cellNumber': 'Cell Number',
          'licenseNo': 'License No',
          'post': 'Post',
          'addLocation': 'Add Location',
          'locationDetails': 'Location Details',
          'countryName': 'Country Name',
          'areaName': 'Area Name',
          'locationName': 'Location Name',
          'latitude': 'Latitude',
          'longitude': 'Longitude',
          'uploadImage': 'Upload Image',
          'selectImage': 'Select Image',
          'propertyUpdatedSuccessfully': 'Property updated successfully',
          'success': 'Success',
          'error': 'Error',
          'addNewStreet': 'Add New Street',
          'streetName': 'Street Name',
          'areaUnit': 'Area Unit',
          'areYouSureYouWantToDeleteThisProperty':
              'Are you sure you want to delete this property?',
          'noPropertiesFound': 'No properties found',
        },
        'es': {}
      };
}
